#!/usr/bin/env python3.3

import sys, time, uuid, requests, os, random, hashlib

endpoint = sys.argv[1]
maximumContentLength = 128

def die(msg):
  sys.stdout.write("ERROR: %s\n" % msg)
  sys.exit(1)

def ok(msg):
  sys.stdout.write("OK: %s\n" % msg)

def good_case():
  i = random.randint(0, maximumContentLength)
  b = os.urandom(i)
  sha = hashlib.sha256()
  sha.update(b)
  return sha.hexdigest(), b

r = requests.get(endpoint)
r.status_code == 200 or die('index not being served')
ok('index retrieved')

good_hex, good_bytes = good_case()
url = "%s/%s" % (endpoint, good_hex)

r = requests.put(url, data=good_bytes)
r.status_code == 201 or die('put failed with status: %s (url: %s)' % (r.status_code, url))
ok('put succeeded: %s' % url)

r = requests.get(url)
r.status_code == 200 or die('tried to get data but got status code: %s' % r.status_code)
ok('get suceeeded')
